// <auto-generated />
using System;
using EFCoreBug;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreBug.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20221129013350_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("EFCoreBug.Snapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id", "VersionNumber");

                    b.ToTable("Snapshots", (string)null);
                });

            modelBuilder.Entity("EFCoreBug.SnapshotReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PointerId")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("PointerVersionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("SnapshotVersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasAlternateKey("PointerId", "PointerVersionNumber");

                    b.HasIndex("SnapshotId", "SnapshotVersionNumber");

                    b.ToTable("SnapshotReferences", (string)null);
                });

            modelBuilder.Entity("EFCoreBug.SnapshotReference", b =>
                {
                    b.HasOne("EFCoreBug.Snapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId", "SnapshotVersionNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });
#pragma warning restore 612, 618
        }
    }
}
