// <auto-generated />
using System;
using EFCoreBug;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreBug.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("EFCoreBug.SnapshotReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PointerId")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("PointerVersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasAlternateKey("PointerId", "PointerVersionNumber");

                    b.ToTable("SnapshotReferences", (string)null);
                });

            modelBuilder.Entity("EFCoreBug.SnapshotReference", b =>
                {
                    b.OwnsMany("EFCoreBug.Snapshot", "Snapshots", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<ulong>("VersionNumber")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("SnapshotReferenceId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id", "VersionNumber");

                            b1.HasIndex("SnapshotReferenceId");

                            b1.ToTable("Snapshots", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SnapshotReferenceId");
                        });

                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
